config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts
  devise_for :ministers
  devise_for :users

  root 'posts#index'

  get 'dashboard' => 'dashboard#index', as: "minister_dashboard"

  resources :posts do
  member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
  end
end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/minister.rb
class Minister < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :taggings
  has_many :posts, through: :taggings
  has_many :updates

  has_attached_file :profile, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :profile, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_many :taggings
  has_many :ministers, through: :taggings
  belongs_to :category
  has_many :updates

  acts_as_votable

  has_attached_file :cover,
                       :styles => {
                       :hero => "1150x420#",
                       :thumb => "350x300#" },
                       :convert_options => {
                       :hero => "-strip",
                       :thumb => "-quality 95 -strip -gravity center" },
                       :default_url => "/images/:style/missing.png"
     validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :minister
  belongs_to :post
end

app/models/update.rb
class Update < ActiveRecord::Base
  belongs_to :post
  belongs_to :minister

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  acts_as_voter


end

app/controllers/application_controller.rb
class Minister::ParameterSanitizer < Devise::ParameterSanitizer
  def sign_in
    default_params.permit(:username, :password, :remember_me)
  end
  def sign_up
    default_params.permit(:username, :email, :password, :password_confirmation, :remember_me, :profile, :name, :title)
  end
  def account_update
    default_params.permit(:username, :email, :password, :password_confirmation, :current_password, :profile, :name, :title)
  end
end

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :profile, :name, :title) }
  #   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :profile, :name, :title) }
  # end

  protected

  def devise_parameter_sanitizer
    if resource_class == Minister
      Minister::ParameterSanitizer.new(Minister, :minister, params)
    else
      super # Use the default one
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @minister = current_minister
    @posts = @minister.posts
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def upvote
  @post = Post.find(params[:id])
  @post.upvote_by current_user
  redirect_to posts_path
end
def downvote
  @post = Post.find(params[:id])
  @post.downvote_by current_user
  redirect_to posts_path
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :cover, :category_id, minister_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>Welcome, <%= @minister.name %>!</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <h2>Causes you have been tagged</h2>
    </div>
  </div>

  <% @posts.in_groups_of(4, false).each do |group| %>
    <div class="row">
      <% group.each do |post| %>
        <div class="col-xs-4 col-sm-3">
          <div class="card">
            <% if post.cover.exists? %>
              <%= image_tag post.cover.url(:thumb), class: 'card-img-top card-img-full' %>
            <% end %>
            <div class="card-block">
              <!-- <a href="#" class="card-link-full"></a> -->
              <%= link_to(post) do %>
                <h3 class="card-title"><%= post.title %></h3>
              <% end %>
              <p class="card-text"><%= (post.get_upvotes.size + 4) * 124 %>-<%= (post.get_downvotes.size + 4) * 124 %></p>
              <!-- <%= button_to "AGREE", like_post_path(post), method: :put, class: 'btn btn-primary' %> -->
              <!-- <%= button_to "DISAGREE", dislike_post_path(post), method: :put, class: 'btn btn-primary' %> -->
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voices</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Work+Sans:300,500,700|Merriweather' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
  <div class="site-notice">
    voices.lk is in beta right now. 
  </div>
  <nav class="navbar navbar-default navbar-custom">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag('logo.png') %>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Start a Cause', new_post_path, class: 'red-link' %></li>
            <li><a href="#">Explore</a></li>
            <% if minister_signed_in? %>
              <li><%= link_to 'Dashboard', minister_dashboard_path, class: 'red-link' %></li>
            <% end %>
            <% if user_signed_in? %>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% elsif minister_signed_in? %>
              <li><%= link_to('Logout', destroy_minister_session_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to('Login', new_user_session_path)  %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

<%= yield %>

<footer class="footer">
  <div class="container">
    <p class="text-muted">&copy; 2015. Voices.lk</p>
  </div>
</footer>

</div>

</body>
</html>

app/views/ministers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/posts/_form.html.erb
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<div class="step well">Step 1</div>
<div class="step well">Step 2</div>
<div class="step well">Step 3</div>
<div class="step well">Step 4</div>
<div class="step well">Step 5</div>
<div class="step well">Step 6</div>
<button class="action back btn btn-info">Back</button>
<button class="action next btn btn-info">Next</button>
<button class="action submit btn btn-success">Submit</button>

<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.trix_editor :content %>
  </div>
  <div class="field">
    <%= f.file_field :cover %>
  </div>
  <div class="field">
    <%= hidden_field_tag "post[minister_ids][]", nil %>
    <% Minister.all.each do |minister| %>
      <%= check_box_tag "post[minister_ids][]", minister.id, @post.minister_ids.include?(minister.id), id: dom_id(minister) %>
      <%= label_tag dom_id(minister), minister.email %><br>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function(){
var current = 1;

widget      = $(".step");
btnnext     = $(".next");
btnback     = $(".back");
btnsubmit   = $(".submit");

// Init buttons and UI
widget.not(':eq(0)').hide();
hideButtons(current);
setProgress(current);

// Next button click action
btnnext.click(function(){
  if(current &lt; widget.length){
                 widget.show();
                 widget.not(':eq('+(current++)+')').hide();
       setProgress(current);
       }
             hideButtons(current);
     })
     // Back button click action
     btnback.click(function(){
              if(current &gt; 1){
    current = current - 2;
    btnnext.trigger('click');
  }
  hideButtons(current);
})
});

// Change progress bar action
setProgress = function(currstep){
var percent = parseFloat(100 / widget.length) * currstep;
percent = percent.toFixed();
$(".progress-bar")
      .css("width",percent+"%")
      .html(percent+"%");
}

// Hide buttons according to the current step
hideButtons = function(current){
var limit = parseInt(widget.length);

$(".action").hide();

if(current &lt; limit) btnnext.show(); 	if(current &gt; 1) btnback.show();
if (current == limit) { btnnext.hide(); btnsubmit.show(); }
}
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form2' %>
<!--
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %> -->

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>
  </div>
</div>

<div class="container-fluid">

  <div class="row text-center hero-banner">
    <div class="col-md-12">
      <div>
         <%= image_tag('par.jpg', class: 'img-responsive center-block') %>
      </div>
      <h1>Digitizing democracy, one cause at a time</h1>
    </div>
    <div class="col-md-12">
      <%= link_to 'Start a Cause', new_post_path, class: 'btn btn-primary btn-lg btn-red' %>
    </div>
  </div>

</div>

<div class="container">
  <div class="row">
    <div class="col-md-12 text-center section-title">
      <h4>Trending Causes</h4>
    </div>
  </div>

  <% @posts.in_groups_of(4, false).each do |group| %>
    <div class="row">
      <% group.each do |post| %>
        <div class="col-xs-4 col-sm-3">
          <div class="card">
            <% if post.cover.exists? %>
              <%= image_tag post.cover.url(:thumb), class: 'card-img-top card-img-full' %>
            <% end %>
            <div class="card-block">
              <!-- <a href="#" class="card-link-full"></a> -->
              <%= link_to(post) do %>
                <h3 class="card-title"><%= post.title %></h3>
              <% end %>
              <p class="card-text"><%= (post.get_upvotes.size + 4) * 124 %>-<%= (post.get_downvotes.size + 4) * 124 %></p>
              <%= button_to "AGREE", like_post_path(post), method: :put, class: 'btn btn-primary' %> 
              <%= button_to "DISAGREE", dislike_post_path(post), method: :put, class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
  <!--
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>

        <td><%= post.title %></td>
        <td><%= post.content.html_safe %></td>
        <td><%= link_to "upvote", like_post_path(post), method: :put %></td>
        <td><%= post.get_upvotes.size %></td>
        <td><%= link_to "downvote", dislike_post_path(post), method: :put %></td>
        <td><%= post.get_downvotes.size %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->

<br>
<!--

<%= link_to 'New Post', new_post_path %>
<% if user_signed_in? %>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <% else %>
            <li><%= link_to('Login', new_user_session_path)  %></li>
          <% end %>
        -->

app/views/posts/new.html.erb
<!-- <div class="container">
  <div class="row">
    <div class="col-md-12 new-post"> -->
      <%= render 'form2' %>
    <!-- </div>
  </div>
</div> -->

<!--
<%= link_to 'Back', posts_path %>
-->

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="post">

  <div class="container">

    <div class="row post-header">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h1 class="post-title"><%= @post.title %></h1>
        <div class="post-header-meta">
          <em>by</em>
          <%= image_tag('profile-img.jpg', class: 'img-circle img-profile-s') %>
          <span>Anonymous User <em>on</em> 21st Nov 2015</span>
        </div>
      </div>
    </div>
    <div class="row post-body">
      <div class="col-md-8">
        <%= image_tag @post.cover.url(:hero), class: 'img-responsive' %>
        <h4 class="section-head">Tagged Ministers</h4>
        <div class="post-mps">
          <% @post.ministers.each do |m| %>
            <div class="profile-card">
              <a href="#" class="profile-pic">
                <%= image_tag m.profile.url(:thumb), class: 'img-circle img-profile-m' %>
              </a>
              <div class="profile-text">
                <%= m.name %><br><span><%= m.title %></span>
              </div>
            </div>
          <% end %>
        </div>
        <div class="post-text">
          <%= @post.content.html_safe %>
        </div>

        <div class="comments">
          <div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//voiceslk2.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
        </div>
      </div>
      <div class="col-md-4 post-stats">
        <div class="supporters">
          <h2 class="number"><%= (@post.get_upvotes.size + 8) * 345 %></h2>
          <span>supporters</span>
        </div>
        <div class="progress">
          <div class="progress-bar progress-bar-primary" style="width: 85%">
            85%
          </div>
          <div class="progress-bar progress-bar-danger" style="width: 15%">
            15%
          </div>
        </div>
        <div class="vote">
          <%= button_to like_post_path(@post), method: :put, class: 'btn btn-primary btn-lg' do %>
            <i class="fa fa-thumbs-o-up fa-lg"></i>Support this cause
          <% end %>
          <%= button_to dislike_post_path(@post), method: :put, class: 'btn btn-danger btn-lg' do %>
            <i class="fa fa-thumbs-o-down fa-lg"></i>
          <% end %>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>